### PR TITLE
feat(tests): universal provider-env isolation fixture (#1405 Fix C)

### PR DESCRIPTION
**Pull request by gltanaka**
## Summary

Implements **Fix C** from `promptdriven/pdd_cloud#1405` ("pdd-issue verifier
should catch env-dependent test isolation bugs"). Fix C targets the
**env-leak** shape: tests that pass on the verifier's minimal worker
container but fail on a developer machine that has provider keys
(`XAI_API_KEY`, `GOOGLE_APPLICATION_CREDENTIALS`, ...) exported.

This is Fix C in the B → C → A sequencing from `promptdriven/pdd_cloud#1405`.
Fix B (`promptdriven/pdd#899`, merged) catches the *hardcoded-list-drift*
shape via static analysis at `pdd checkup` time. Fix C catches the
*env-leak* shape at the test-fixture layer.

Sibling PRs:
- `promptdriven/pdd#899` (Fix B — merged)
- `promptdriven/pdd#900` (Gemini 3 temperature clamp — merged)
- `promptdriven/pdd#901` (Fix B polish — open)

## What lands

An autouse fixture `_isolate_provider_env` in `tests/conftest.py` that
clears every provider credential env var the OpenCode code path consults,
before each test runs. Tests opt back in via `monkeypatch.setenv` /
`patch.dict(os.environ, {...})`.

Cross-repo reference: `promptdriven/pdd_cloud#1405`.

## Canonical source decision

Keys are sourced from `pdd.agentic_common._opencode_provider_env_keys()` —
the same runtime helper the production code path uses to decide whether
to trust an OpenCode credential signal.

**Why the runtime helper and not the literal fallback constant?**

1. The 26-key `_OPENCODE_PROVIDER_ENV_KEYS_FALLBACK` literal only covers
   the CSV-loading-broken case. The 45-key runtime set is what the
   production code path actually consults. Using the fallback would leak
   the 19 CSV-only keys (`GOOGLE_APPLICATION_CREDENTIALS`,
   `VERTEXAI_PROJECT`, `WANDB_API_KEY`, ...) — exactly the developer-machine
   vectors named in `promptdriven/pdd_cloud#1405`.

2. A new literal-tuple consumer in `tests/conftest.py` would be flagged
   as drift by Fix B's static-analysis detector (`promptdriven/pdd#899`).
   Sourcing from the runtime helper keeps Fix C out of its own bug class.

The helper is imported lazily inside the fixture body (not at conftest
module load) so it does not pull `litellm` into the import graph for
trivial test sessions — same pattern as the existing
`_isolate_claude_oauth_probe` / `_isolate_codex_auth_file` fixtures.

## Opt-back-in contract

Tests that legitimately need a credential set must populate it
themselves:

```python
def test_needs_anthropic_key(monkeypatch):
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-test-key")
    ...  # autouse fixture cleared it; setenv puts it back for this test
```

pytest tears down fixtures in reverse order, so a test that wraps its
body in `patch.dict(os.environ, {...}, clear=True)` (e.g.
`test_agentic_common_issue_813_anthropic_api_key_oauth_shadow.py`) sees
its own env, undoes that before the autouse fixture's monkeypatch
unwinds, and never leaks the developer's real env across the boundary.

This is verified by the new regression tests
(`tests/test_provider_env_isolation.py::test_tests_can_opt_back_in_via_monkeypatch`).

## TDD evidence

The branch follows strict TDD with three commits in this order:

1. `bcd9189e` — `test(env-isolation): failing tests for autouse
   provider-env fixture (#1405 Fix C)`. Adds
   `tests/test_provider_env_isolation.py`. On a developer shell that
   exports `XAI_API_KEY`, `GOOGLE_APPLICATION_CREDENTIALS`,
   `VERTEXAI_PROJECT`, `ANTHROPIC_API_KEY`, etc., 5 of the 7 new tests
   fail with the canonical-source leak shape this PR exists to prevent.
2. `1bd854ec` — `feat(tests): universal provider-env isolation fixture
   (#1405 Fix C)`. Adds the autouse fixture in `tests/conftest.py`.
   All 7 of the new tests now pass; the fail-first contract is the
   evidence the fixture actually fired.
3. `697c0350` — `test(env-isolation): silence Fix B detector
   false-positive in #1405 Fix C`. Derives the `must_cover` set inside
   `test_canonical_source_includes_developer_leak_vectors` from
   `_LEAK_PROBE_KEYS` rather than re-declaring a 3-item literal, so that
   running Fix B's detector on this PR's touched files emits exactly
   zero findings (was 1 false-positive before).

## No new hardcoded env-key list

Confirmed by Fix B's detector on the touched files:

```
$ python -c "from pathlib import Path; \
              from pdd.list_drift_detection import detect_static_list_drift; \
              print(detect_static_list_drift([Path('tests/conftest.py'), \
                                              Path('tests/test_provider_env_isolation.py'), \
                                              Path('pdd/agentic_common.py')]))"
[]
```

## Breakage report (full test-suite delta)

Ran `pytest tests/ -q --tb=no -p no:cacheprovider --ignore=tests/test_provider_env_isolation.py`
before and after the fixture on the same developer shell (with real
`XAI_API_KEY`, `GOOGLE_APPLICATION_CREDENTIALS`, etc. exported):

| Phase    | Failed | Passed | Skipped | xfailed | Duration |
|----------|-------:|-------:|--------:|--------:|---------:|
| Baseline |     54 |   8092 |      61 |       1 |   18m05s |
| Fix C    |     55 |   8090 |      62 |       1 |   16m43s |
| Delta    |     +1 |     -2 |      +1 |       0 |          |

**Net effect of the fixture itself: zero new failures attributable to
env isolation.** A diff of the failing-test names between Fix C and
baseline reveals exactly one test that differs:
`tests/test_generate_test.py::test_generate_test_maximum_values`, a
flaky `Lm_studioException - Connection error` that passes in isolation
(`pytest tests/test_generate_test.py::test_generate_test_maximum_values`
returns green on 3 consecutive re-runs) and is unrelated to provider
env vars.

**Taxonomy of the 55 fix-C failures** (54 also present in baseline; not
caused by Fix C):

- 17 × `ValueError: PDD_PATH environment variable is not set` — pre-existing
  PDD test infrastructure issue, unrelated to provider env vars.
- 12 × `test_fix_error_loop*` mock-call-count assertions — pre-existing
  test-state issues.
- 12 × `test_fix_main` cloud-mode mock-call assertions — pre-existing.
- 5 × `test_sync_code_main` PDD_PATH issues — pre-existing.
- 3 × `test_user_story_tests` "Code file not found" — pre-existing.
- 1 × `test_version` 0.0.230 vs 0.0.233 — local pip-install staleness.
- 1 × `test_generate_test_maximum_values` LM Studio connection — flaky,
  passes in isolation.
- 1 × `test_sync_order` lisp module — pre-existing.
- 2 × `test_postprocess_0` regex assertion — pre-existing.
- 1 × `test_connect_custom_host_port` — pre-existing.
- 1 × `test_agentic_fix.py::TestCwdHandling::test_run_agentic_fix_respects_cwd_parameter`
  — pre-existing (also fails with `PDD_PATH not set` in the captured stderr).

The critical regression files — `tests/test_agentic_common.py`,
`tests/test_opencode_provider.py`,
`tests/test_agentic_common_issue_813_anthropic_api_key_oauth_shadow.py`
— all pass with the fixture installed. These are the files where the
`promptdriven/pdd#858` 7-test env-isolation bug shipped, and they
remain green.

## What this PR does NOT do

- Does not change the canonical source (`_opencode_provider_env_keys`)
  or the fallback constant. This PR adds a consumer, not a new producer.
- Does not clear non-credential env vars like `OPENCODE_CONFIG` and
  `OPENCODE_CONFIG_CONTENT`. Those are config-file pointers, not provider
  credentials, and the established pattern in
  `tests/test_opencode_provider.py::_clear_all_opencode_provider_env`
  is to clear them per-test alongside the canonical set when needed.
- Does not silence any of the 54 pre-existing baseline failures —
  those are out of scope for this PR (PDD_PATH, mock wiring, version
  drift, LM Studio flakes are tracked separately).
- Does not implement Fix A (fat-container variant) from
  `promptdriven/pdd_cloud#1405` — that is an explicit follow-up after
  B+C produce data on what they miss.

## Test plan

- [x] `pytest tests/test_provider_env_isolation.py` — 7 passed
- [x] `pytest tests/test_agentic_common.py tests/test_opencode_provider.py tests/test_agentic_common_issue_813_anthropic_api_key_oauth_shadow.py tests/test_setup_tool.py tests/test_cli_detector.py` — all pass
- [x] `pytest tests/test_llm_invoke.py tests/test_e2e_issue_342_syspath_isolation.py` — all pass
- [x] `pytest tests/test_sync_orchestration.py` — all pass
- [x] `pytest tests/ -q --tb=no` (full suite) — 55 failed (54 pre-existing baseline failures + 1 flaky LM Studio), 8090 passed, 62 skipped
- [x] Fix B detector emits zero findings on touched files
- [ ] `/gcbrun` (Cloud Batch full suite — posted below)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by gltanaka — COMMENTED** [review]
## Verdict (iter 1)
APPROVE

I cannot self-approve (this is a peer review comment, not an `--approve` review), but every blocker I came in looking for has been disproven by independent verification on a fresh checkout. CI is fully green. Ship it.

## Blockers (must fix before merge)
None.

## Majors (should fix; merge if implementer commits to follow-up)
None.

## Minors
- `LMSTUDIO_HOST` and `OLLAMA_HOST` ARE in the canonical 45-key set and get cleared by the fixture, but the production LM Studio code path in `pdd/llm_invoke.py:3249` and `pdd/model_tester.py:103` reads `LM_STUDIO_API_BASE` (different spelling). Not a regression — LM Studio tests aren't fixture-coupled — but if anyone ever adds a test that depends on `LMSTUDIO_HOST`/`OLLAMA_HOST` being set in env, they'll need to `monkeypatch.setenv` it. Worth a one-line note in the fixture docstring on a future polish pass; not blocking.
- `GITHUB_TOKEN` is in the canonical set and gets cleared. All grep-found test usages either delenv it themselves or setenv it explicitly, so no current tests break. Worth keeping an eye on if anyone adds a test that relies on the CI runner's pre-set `GITHUB_TOKEN`.

## What this does well
- Strict TDD: `bcd9189e` (failing tests) lands before `1bd854ec` (fixture), verifiable in `git log --oneline origin/main..HEAD`. The red phase reproduces cleanly — reverting only `tests/conftest.py` to origin/main while keeping the new tests yields 5/7 failures with the exact leak shape the fixture exists to prevent.
- Canonical source is the runtime helper `_opencode_provider_env_keys()` (45 keys), not the 26-key `_OPENCODE_PROVIDER_ENV_KEYS_FALLBACK` literal. Confirmed by `len(_opencode_provider_env_keys()) == 45` and the CSV-only delta includes `GOOGLE_APPLICATION_CREDENTIALS`, `VERTEXAI_PROJECT`, `VERTEXAI_LOCATION`, `WANDB_API_KEY`, and the 15 newer provider keys — exactly the developer-machine leak vectors named in #1405.
- Fix B's static-analysis detector returns 0 findings on `tests/conftest.py` + `pdd/agentic_common.py`, so Fix C does not introduce its own Fix B regression. Verified by running `detect_static_list_drift([Path('tests/conftest.py'), Path('pdd/agentic_common.py')])` on this branch.
- The `from pdd.agentic_common import _opencode_provider_env_keys` import is inside the fixture body (line 156), not at conftest module top. The lazy-import claim holds: `litellm` is already in `sys.modules` after `import tests.conftest` only because conftest's existing top-level `from pdd.llm_invoke import InsufficientCreditsError` (line 10) pulls it in — that pre-dates this PR. The new fixture adds zero modules to conftest's import graph.
- Don't-clear list is correct: no `PYTEST_*`, `PDD_*`, `PATH`, `HOME`, `CI`, `GITHUB_ACTIONS`, `GITHUB_WORKSPACE`, or `LITELLM_CACHE_*` is in the canonical set. The set is purely provider credentials.
- Opt-back-in contract works: `test_tests_can_opt_back_in_via_monkeypatch` passes, all 47 #813 OAuth-shadow tests pass (these are the `patch.dict(clear=True)` cases the implementer specifically called out), all 348 critical regression tests across `test_agentic_common.py` + `test_opencode_provider.py` + `test_agentic_common_issue_813_anthropic_api_key_oauth_shadow.py` are green.
- Scope is minimal: only `tests/conftest.py` (+49) and `tests/test_provider_env_isolation.py` (+165, new). No `pdd/*` source touched. `git diff origin/main..HEAD --name-only` confirms.

## Verification I did
- **TDD reproduction**: Cloned fresh at `/tmp/pr-902-review`, checked out `pr-902`, copied PR's `tests/conftest.py` aside, replaced with origin/main's version. Ran `pytest tests/test_provider_env_isolation.py -v` → 5 failed, 2 passed (the 2 that pass without the fixture are the canonical-source-coverage and opt-back-in invariants, which don't exercise the fixture). Restored the PR's conftest → 7/7 pass. Red→green confirmed.
- **Fix B detector run**: `detect_static_list_drift([Path('tests/conftest.py'), Path('pdd/agentic_common.py')])` → `finding count: 0`. No new hardcoded list introduced.
- **+1 failure investigation**: `pytest tests/test_generate_test.py::test_generate_test_maximum_values -v` → PASSED on this developer machine. Re-ran with `env -i HOME=$HOME PATH=$PATH` (mimicking the fixture's clean-env effect) → still PASSED. Full `pytest tests/test_generate_test.py` → 21/21 passed. Verified `LM_STUDIO_API_BASE` (the actual env the production LM Studio path reads) is NOT in the canonical 45-key set, so the fixture cannot have caused this flake. Implementer's "flaky LM Studio connection" attribution is sound.
- **Baseline parity spot-check**: Ran `pytest tests/test_fix_error_loop.py` and `pytest tests/test_user_story_tests.py` on origin/main's conftest → confirmed `test_fix_error_loop_*` mock-count failures and `test_user_story_fix_happy_path` "Code file not found" failures BOTH pre-exist on origin/main. Same failures appear with Fix C's conftest. Implementer's "55 failures, all pre-existing" taxonomy is credible. The PDD_PATH bucket is also reproducible (e.g., `test_verify_independently_uses_config_dir_not_repo_root` fails identically on origin/main with `ValueError: PDD_PATH environment variable is not set`).
- **45-key claim**: `len(_opencode_provider_env_keys()) == 45`. CSV-only delta = 19 keys (the canonical set minus the fallback). All leak vectors named in #1405 covered: `XAI_API_KEY`, `GOOGLE_APPLICATION_CREDENTIALS`, `VERTEXAI_PROJECT`, `ANTHROPIC_API_KEY` — all present.
- **Lazy-import claim**: `from pdd.agentic_common import _opencode_provider_env_keys` is on line 156, inside the fixture function body. Verified by reading the diff and the file.
- **Critical regression coverage** (with fix in place):
  - `tests/test_agentic_common.py` + `tests/test_opencode_provider.py` + `tests/test_agentic_common_issue_813_anthropic_api_key_oauth_shadow.py`: 348 passed
  - `tests/test_setup_tool.py` + `tests/test_cli_detector.py`: 89 passed
  - `tests/test_llm_invoke.py` + `tests/test_track_cost.py` + `tests/test_duplicate_cli_guard.py`: 353 passed
  - `tests/test_sync_orchestration.py`: 177 passed
  - `tests/test_e2e_issue_342_syspath_isolation.py`: 4 passed
  - `tests/test_list_drift_detection.py` (Fix B's own tests): 22 passed
- **CI status**: All 7 checks green. `Run Unit Tests` 5m47s, `Public CLI Regression` 2m23s, `Package Preprocess Smoke` 1m13s, CodeQL (3 analyses) pass.
- **Adversarial — subprocess env propagation**: The 2 tests in `tests/test_sync_orchestration.py` that pass `env=os.environ.copy()` to subprocesses run `python <file>` for `print('hello')`; they don't need provider keys, so the cleared environment is fine. Behavior (cleared keys propagate to subprocesses) is desirable.
- **Adversarial — module-load env reads**: `tests/test_opencode_provider.py` imports from `pdd.agentic_common` at top level; `agentic_common` reads env only in function bodies, not at module-load time. 348 tests across that file family green confirms there is no module-load-time leak path.
